<a href="https://colab.research.google.com/github/mubarakdalvi/myprojects/blob/main/Logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import libraries , numpy ,pandas,seaborn,matpotlib,sklearn

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression

upload csv,xml,json,psv,or any other file from local host

In [ ]:
from google.colab import files
data = files.upload()

convert to data frame using respected pd.to_csv mthod

In [ ]:
df = pd.read_csv('titanic.csv')

check head and tail of df  for cheking data error,na values,any column not named

In [ ]:
df.head()

for info about df for any missing valus or not.

In [ ]:
df.info()

CLeansing And preproccessing the data

geting unique value of survived array from df

In [ ]:
df['survived'].unique()

array([0, 1])

checking correlation if value is direcly proportional or invervsly proportional ,means close to -1 or 1 just like in below df if value is close t zero then it have less correlation eg, 0.00001,-0.00020

In [ ]:
df.corr()

<ipython-input-7-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


survived    pclass       age     sibsp     parch      fare  \
survived    1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307   
pclass     -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500   
age        -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067   
sibsp      -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651   
parch       0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225   
fare        0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000   
adult_male -0.557080  0.094035  0.280328 -0.253586 -0.349943 -0.182024   
alone      -0.203367  0.135207  0.198270 -0.584471 -0.583398 -0.271832   

            adult_male     alone  
survived     -0.557080 -0.203367  
pclass        0.094035  0.135207  
age           0.280328  0.198270  
sibsp        -0.253586 -0.584471  
parch        -0.349943 -0.583398  
fare         -0.182024 -0.271832  
adult_male    1.000000  0.404744  
alone         0.404744  1.000000

In [ ]:
df['pclass'].unique()

array([3, 1, 2])

df is group by pclass and getting mean of it to get mean value age by class just shwon in the below code

In [ ]:
df.groupby('pclass').mean()

<ipython-input-9-c526dc643741>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('pclass').mean()


survived        age     sibsp     parch       fare  adult_male  \
pclass                                                                   
1       0.629630  38.233441  0.416667  0.356481  84.154687    0.550926   
2       0.472826  29.877630  0.402174  0.380435  20.662183    0.538043   
3       0.242363  25.140620  0.615071  0.393075  13.675550    0.649695   

           alone  
pclass            
1       0.504630  
2       0.565217  
3       0.659878

modifying the data for filing the empty and na values

In [ ]:
def impute_age(col):
  age = col[1]
  pclass = col[0]
  if pd.isnull(age):
    if pclass == 1:
      return 38
    elif pclass == 2:
      return 30
    else:
      return 25
  else:
    return age

applying this code to df's colum named age using apply due to having two inputs as pclass and age we have to put axis = 1 also , when axis = 0 this will apply on row and code will execute but age value will be 0

In [ ]:
df['age'] = df[['pclass','age']].apply(impute_age,axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   survived    891 non-null    int64  
 1   pclass      891 non-null    int64  
 2   age         891 non-null    int64  
 3   sibsp       891 non-null    int64  
 4   parch       891 non-null    int64  
 5   fare        891 non-null    float64
 6   embarked    891 non-null    float64
 7   who         891 non-null    int64  
 8   adult_male  891 non-null    int64  
 9   alone       891 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 69.7 KB


In [ ]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
df['embark_town'].unique()
df.drop('embark_town',axis=1,inplace=True)

In [ ]:
df['embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

as per above code embarked have 3 values and we have to change its type to check its correclations and to check whearter this will impact the data or not,
as below code we have used replace on df['embarked'] to replace value by 1,2,3

In [ ]:
df['embarked'].replace(['S','C','Q'],[0,1,2],inplace=True)

In [ ]:
df.corr()

<ipython-input-17-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


survived    pclass       age     sibsp     parch      fare  \
survived    1.000000 -0.338481 -0.050156 -0.035322  0.081629  0.257307   
pclass     -0.338481  1.000000 -0.404262  0.083081  0.018443 -0.549500   
age        -0.050156 -0.404262  1.000000 -0.243549 -0.175264  0.121044   
sibsp      -0.035322  0.083081 -0.243549  1.000000  0.414838  0.159651   
parch       0.081629  0.018443 -0.175264  0.414838  1.000000  0.216225   
fare        0.257307 -0.549500  0.121044  0.159651  0.216225  1.000000   
embarked    0.108669  0.043835 -0.035787 -0.060606 -0.079320  0.063462   
adult_male -0.557080  0.094035  0.243718 -0.253586 -0.349943 -0.182024   
alone      -0.203367  0.135207  0.170333 -0.584471 -0.583398 -0.271832   

            embarked  adult_male     alone  
survived    0.108669   -0.557080 -0.203367  
pclass      0.043835    0.094035  0.135207  
age        -0.035787    0.243718  0.170333  
sibsp      -0.060606   -0.253586 -0.584471  
parch      -0.079320   -0.349943 -0.583398  
fare        0.063462   -0.182024 -0.271832  
embarked    1.000000   -0.110351  0.018867  
adult_male -0.110351    1.000000  0.404744  
alone       0.018867    0.404744  1.000000

group by survived columns to get mean of data frame

In [ ]:
df.groupby('survived').mean()

<ipython-input-18-779527596371>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('survived').mean()


pclass        age     sibsp     parch       fare  embarked  \
survived                                                                 
0         2.531876  29.787796  0.553734  0.329690  22.117887  0.307832   
1         1.950292  28.425936  0.473684  0.464912  48.395408  0.450000   

          adult_male     alone  
survived                        
0           0.817851  0.681239  
1           0.257310  0.476608

In [ ]:
df['embarked'].replace(np.nan,inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   survived    891 non-null    int64  
 1   pclass      891 non-null    int64  
 2   sex         891 non-null    object 
 3   age         891 non-null    float64
 4   sibsp       891 non-null    int64  
 5   parch       891 non-null    int64  
 6   fare        891 non-null    float64
 7   embarked    891 non-null    float64
 8   class       891 non-null    object 
 9   who         891 non-null    object 
 10  adult_male  891 non-null    bool   
 11  deck        203 non-null    object 
 12  alive       891 non-null    object 
 13  alone       891 non-null    bool   
dtypes: bool(2), float64(3), int64(4), object(5)
memory usage: 85.4+ KB


using df.drop method to drop or delete the column or row if axis = 0 then it will delete row

In [ ]:
df.drop('deck',axis=1,inplace=True)

In [ ]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare  embarked  class  \
0         0       3    male  22.0      1      0   7.2500       0.0  Third   
1         1       1  female  38.0      1      0  71.2833       1.0  First   
2         1       3  female  26.0      0      0   7.9250       0.0  Third   
3         1       1  female  35.0      1      0  53.1000       0.0  First   
4         0       3    male  35.0      0      0   8.0500       0.0  Third   

     who  adult_male alive  alone  
0    man        True    no  False  
1  woman       False   yes  False  
2  woman       False   yes   True  
3  woman       False   yes  False  
4    man        True    no   True

In [ ]:
df['sex'].unique()

array(['male', 'female'], dtype=object)

using pd.get dummies for out gender values that are male female that will be replaced by 0 for male and 1 for female

In [ ]:
gender = pd.get_dummies(df['sex'],drop_first=True)

In [ ]:
df

survived  pclass     sex   age  sibsp  parch     fare  embarked   class  \
0           0       3    male  22.0      1      0   7.2500       0.0   Third   
1           1       1  female  38.0      1      0  71.2833       1.0   First   
2           1       3  female  26.0      0      0   7.9250       0.0   Third   
3           1       1  female  35.0      1      0  53.1000       0.0   First   
4           0       3    male  35.0      0      0   8.0500       0.0   Third   
..        ...     ...     ...   ...    ...    ...      ...       ...     ...   
886         0       2    male  27.0      0      0  13.0000       0.0  Second   
887         1       1  female  19.0      0      0  30.0000       0.0   First   
888         0       3  female  25.0      1      2  23.4500       0.0   Third   
889         1       1    male  26.0      0      0  30.0000       1.0   First   
890         0       3    male  32.0      0      0   7.7500       2.0   Third   

       who  adult_male alive  alone  
0      man        True    no  False  
1    woman       False   yes  False  
2    woman       False   yes   True  
3    woman       False   yes  False  
4      man        True    no   True  
..     ...         ...   ...    ...  
886    man        True    no   True  
887  woman       False   yes   True  
888  woman       False    no  False  
889    man        True   yes   True  
890    man        True    no   True  

[891 rows x 13 columns]

droppping class and sex column cause they have object values and after inserting same details in int manner in other column then other values dosnt take any importance

In [ ]:
df.drop(['class','sex'],axis=1,inplace=True)

imputing alive where value is tru or false

In [ ]:
def impute_alone(col):
  if col == True:
    return 1
  else:
    return 0

In [ ]:
df['alone'] = df['alone'].apply(impute_alone)

In [ ]:
df.head()

survived  pclass   age  sibsp  parch     fare  embarked    who  adult_male  \
0         0       3  22.0      1      0   7.2500       0.0    man        True   
1         1       1  38.0      1      0  71.2833       1.0  woman       False   
2         1       3  26.0      0      0   7.9250       0.0  woman       False   
3         1       1  35.0      1      0  53.1000       0.0  woman       False   
4         0       3  35.0      0      0   8.0500       0.0    man        True   

  alive  alone  
0    no      0  
1   yes      0  
2   yes      1  
3   yes      0  
4    no      1

is man willl check in who column tha man or female

In [ ]:
def is_man(col):
  if col == True:
    return 1
  else:
    return 0
df['adult_male'] = df['adult_male'].apply(is_man)

In [ ]:
df['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

In [ ]:
def impute_who(col):
  if col == 'child':
    return 2
  elif col == 'man':
    return 1
  elif col == 'woman':
    return 0

df['who'] = df['who'].apply(impute_who)

In [ ]:
df.head()

survived  pclass   age  sibsp  parch     fare  embarked  who  adult_male  \
0         0       3  22.0      1      0   7.2500       0.0    1           1   
1         1       1  38.0      1      0  71.2833       1.0    0           0   
2         1       3  26.0      0      0   7.9250       0.0    0           0   
3         1       1  35.0      1      0  53.1000       0.0    0           0   
4         0       3  35.0      0      0   8.0500       0.0    1           1   

  alive  alone  
0    no      0  
1   yes      0  
2   yes      1  
3   yes      0  
4    no      1

In [ ]:
df['alive'].unique()

array(['no', 'yes'], dtype=object)

checking corr and now all values are are present and have corr and now avaiable for next process

In [ ]:
df.corr()

<ipython-input-35-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


survived    pclass       age     sibsp     parch      fare  \
survived    1.000000 -0.338481 -0.050156 -0.035322  0.081629  0.257307   
pclass     -0.338481  1.000000 -0.404262  0.083081  0.018443 -0.549500   
age        -0.050156 -0.404262  1.000000 -0.243549 -0.175264  0.121044   
sibsp      -0.035322  0.083081 -0.243549  1.000000  0.414838  0.159651   
parch       0.081629  0.018443 -0.175264  0.414838  1.000000  0.216225   
fare        0.257307 -0.549500  0.121044  0.159651  0.216225  1.000000   
embarked    0.113083  0.037256 -0.027615 -0.062233 -0.080858  0.066980   
who        -0.325753  0.196793 -0.343079  0.136003  0.055682 -0.146290   
adult_male -0.557080  0.094035  0.243718 -0.253586 -0.349943 -0.182024   
alone      -0.203367  0.135207  0.170333 -0.584471 -0.583398 -0.271832   

            embarked       who  adult_male     alone  
survived    0.113083 -0.325753   -0.557080 -0.203367  
pclass      0.037256  0.196793    0.094035  0.135207  
age        -0.027615 -0.343079    0.243718  0.170333  
sibsp      -0.062233  0.136003   -0.253586 -0.584471  
parch      -0.080858  0.055682   -0.349943 -0.583398  
fare        0.066980 -0.146290   -0.182024 -0.271832  
embarked    1.000000 -0.107915   -0.114625  0.022024  
who        -0.107915  1.000000    0.437532 -0.006540  
adult_male -0.114625  0.437532    1.000000  0.404744  
alone       0.022024 -0.006540    0.404744  1.000000

In [ ]:
df['alone'].unique()

array([0, 1])

In [ ]:
df['alone'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: alone
Non-Null Count  Dtype
--------------  -----
891 non-null    int64
dtypes: int64(1)
memory usage: 7.1 KB


In [ ]:
df['alone'].unique()

array([0, 1])

In [ ]:
df = df.drop('alive',axis=1)

In [ ]:
df['parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [ ]:
x = df.drop('survived',axis=1)

In [ ]:
x.head()

pclass   age  sibsp  parch     fare  embarked  who  adult_male  alone
0       3  22.0      1      0   7.2500       0.0    1           1      0
1       1  38.0      1      0  71.2833       1.0    0           0      0
2       3  26.0      0      0   7.9250       0.0    0           0      1
3       1  35.0      1      0  53.1000       0.0    0           0      0
4       3  35.0      0      0   8.0500       0.0    1           1      1

In [ ]:
y = df['survived']

In [ ]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

importing model  selection for slpiting data with training data sixe = 0.8 so other data wil be assign to test

*   x_train
*   x_test
*   x_train
*   y_test





In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,train_size=0.8)

creating object lr

In [ ]:
lr = LogisticRegression()

checking x_train have how mnay rows and col

In [ ]:
x_train.shape

(712, 9)

training machine on data  to get best input via lm.fit

In [ ]:
lr.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

predicting data that is passed to x_test for getting result

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1])

accurqacy and result we have to library as below

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
confusion_matrix(y_test,y_pred)

array([[91, 19],
       [22, 47]])

In [ ]:
accuracy_score(y_test,y_pred)

0.770949720670391

This Data have accuracy of 0.770949720670391